require('dotenv').config()
const mongoose = require('mongoose')
const Product = require('./models/Product')

const sampleProducts = [
  // ---------------- GUITARS ----------------
  {
    name: 'Fender Squier Affinity Series Stratocaster HSS',
    description: 'Entry-level electric guitar with a humbucker + two single-coils, great beginner Strat.',
    price: 65999,
    category: 'Guitars',
    brand: 'Fender',
    sku: 'GTR-SQR-STRATHSS-001',
    stock: 15,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L84423000002000-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Poplar', strings: 6, pickups: 'HSS' },
  },
  {
    name: 'Fender Player Stratocaster',
    description: 'Fender\'s core-lineup electric guitar, alder body, classic Strat tone for gigging players.',
    price: 241999,
    category: 'Guitars',
    brand: 'Fender',
    sku: 'GTR-FEN-PLYRSTRAT-001',
    stock: 6,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/M11731000001000-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Alder', strings: 6, pickups: 'Single-coil x3' },
  },
  {
    name: "Gibson Les Paul Standard '50s",
    description: 'Classic mahogany/maple Les Paul with a rich, warm humbucker tone. A true flagship electric.',
    price: 769999,
    category: 'Guitars',
    brand: 'Gibson',
    sku: 'GTR-GIB-LP50S-001',
    stock: 2,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L54575000002000-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Mahogany/Maple', strings: 6, pickups: 'Humbucker x2' },
  },
  {
    name: "Epiphone Les Paul Standard '50s",
    description: 'The affordable Epiphone take on the Les Paul Standard, same classic look and warm tone.',
    price: 184999,
    category: 'Guitars',
    brand: 'Epiphone',
    sku: 'GTR-EPI-LP50S-001',
    stock: 8,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/000000122584318-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Mahogany', strings: 6, pickups: 'Humbucker x2' },
  },
  {
    name: 'Ibanez GRX70QA',
    description: 'Affordable Ibanez electric guitar with a quilted maple top, fast slim neck for lead playing.',
    price: 79999,
    category: 'Guitars',
    brand: 'Ibanez',
    sku: 'GTR-IBZ-GRX70QA-001',
    stock: 10,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/000000122571995-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Maple/Basswood', strings: 6, pickups: 'Humbucker x2' },
  },
  {
    name: 'Yamaha FG800 Acoustic Guitar',
    description: 'Solid spruce top acoustic guitar, one of the best-selling beginner-to-intermediate acoustics.',
    price: 65999,
    category: 'Guitars',
    brand: 'Yamaha',
    sku: 'GTR-YAM-FG800-001',
    stock: 12,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L95480000001000-00-600x600.jpg'],
    audioSample: null,
    specs: { topWood: 'Solid Spruce', strings: 6, bodyShape: 'Dreadnought' },
  },
  {
    name: 'Taylor GS Mini Mahogany',
    description: 'Compact, full-toned acoustic guitar, great travel size with big-guitar sound.',
    price: 142999,
    category: 'Guitars',
    brand: 'Taylor',
    sku: 'GTR-TLR-GSMINI-001',
    stock: 5,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/000000122526341-00-600x600.jpg'],
    audioSample: null,
    specs: { topWood: 'Solid Mahogany', strings: 6, bodyShape: 'GS Mini' },
  },
  {
    name: 'Ibanez SR300E Bass Guitar',
    description: 'Lightweight 4-string electric bass, active EQ, comfortable for beginner-to-intermediate bassists.',
    price: 113999,
    category: 'Guitars',
    brand: 'Ibanez',
    sku: 'GTR-IBZ-SR300E-001',
    stock: 7,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/J27307000019000-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Mahogany', strings: 4, pickups: 'Humbucker x2 Active' },
  },
  {
    name: 'Squier Affinity Precision Bass',
    description: 'Classic P-Bass tone at a beginner-friendly price, punchy split-coil pickup.',
    price: 84999,
    category: 'Guitars',
    brand: 'Squier',
    sku: 'GTR-SQR-PBASS-001',
    stock: 9,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L70897000001000-00-600x600.jpg'],
    audioSample: null,
    specs: { bodyWood: 'Poplar', strings: 4, pickups: 'Split single-coil' },
  },

  // ---------------- KEYBOARDS ----------------
  {
    name: 'Yamaha P-125 Digital Piano',
    description: '88-key weighted digital piano, great for beginners and stage use.',
    price: 189999,
    category: 'Keyboards',
    brand: 'Yamaha',
    sku: 'KEY-YAM-P125-001',
    stock: 8,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L19002000001001-00-600x600.jpg'],
    audioSample: null,
    specs: { keys: 88, weighted: true, polyphony: 192 },
  },
  {
    name: 'Casio CT-S300 Portable Keyboard',
    description: 'Compact 61-key portable keyboard, easy for beginners, built-in lesson mode.',
    price: 54999,
    category: 'Keyboards',
    brand: 'Casio',
    sku: 'KEY-CAS-CTS300-001',
    stock: 15,
    images: ['https://m1.com.pk/wp-content/uploads/2020/11/Casio-Casiotone-CT-S300.jpg'],
    audioSample: null,
    specs: { keys: 61, weighted: false, polyphony: 48 },
  },
  {
    name: 'Roland FP-30X Digital Piano',
    description: 'Portable digital piano with authentic hammer-action feel and Roland\'s acclaimed piano sound engine.',
    price: 213999,
    category: 'Keyboards',
    brand: 'Roland',
    sku: 'KEY-ROL-FP30X-001',
    stock: 6,
    images: ['https://kraftmusic.com/cdn/shop/files/ROL-FP30X_Style-Shots-14.jpg?v=1770225537&width=3000'],
    audioSample: null,
    specs: { keys: 88, weighted: true, polyphony: 256 },
  },
  {
    name: 'Korg PA-1000 Arranger Keyboard',
    description: 'Professional arranger keyboard with built-in auto-accompaniment, used widely by live performers.',
    price: 484999,
    category: 'Keyboards',
    brand: 'Korg',
    sku: 'KEY-KRG-PA1000-001',
    stock: 3,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/K44910000000000-00-600x600.jpg'],
    audioSample: null,
    specs: { keys: 61, weighted: false, polyphony: 128 },
  },
  {
    name: 'Yamaha PSR-E373 Portable Keyboard',
    description: 'Beginner-friendly 61-key keyboard with a huge built-in voice and style library.',
    price: 58999,
    category: 'Keyboards',
    brand: 'Yamaha',
    sku: 'KEY-YAM-PSRE373-001',
    stock: 12,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/000000122803870-00-600x600.jpg'],
    audioSample: null,
    specs: { keys: 61, weighted: false, polyphony: 48 },
  },

  // ---------------- DRUMS ----------------
  {
    name: 'Pearl Export Series Drum Kit',
    description: '5-piece drum kit, great all-around beginner-to-intermediate set.',
    price: 227999,
    category: 'Drums',
    brand: 'Pearl',
    sku: 'DRM-PRL-EXPORT-001',
    stock: 5,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/H94538000005000-00-600x600.jpg'],
    audioSample: null,
    specs: { pieces: 5, shellMaterial: 'Poplar/Asian Mahogany' },
  },
  {
    name: 'Roland TD-1DMK Electronic Drum Kit',
    description: 'Compact electronic drum kit with mesh heads, quiet practice with realistic feel.',
    price: 142999,
    category: 'Drums',
    brand: 'Roland',
    sku: 'DRM-ROL-TD1DMK-001',
    stock: 4,
    images: ['https://m1.com.pk/wp-content/uploads/2020/12/Roland-TD-1DMK-Electronic-Drums-458x458.jpg'],
    audioSample: null,
    specs: { pieces: 5, pads: 'Mesh head', module: 'TD-1' },
  },
  {
    name: 'Ludwig Breakbeats by Questlove Kit',
    description: 'Compact 4-piece drum kit designed for small spaces without losing full-size tone.',
    price: 142999,
    category: 'Drums',
    brand: 'Ludwig',
    sku: 'DRM-LUD-BREAKBEATS-001',
    stock: 3,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/L95201000001000-00-2000x2000.jpg'],
    audioSample: null,
    specs: { pieces: 4, shellMaterial: 'Poplar' },
  },
  {
    name: 'Zildjian A Custom 14" Hi-Hat Cymbals',
    description: 'Bright, cutting hi-hat pair, a favorite among gigging drummers for its crisp attack.',
    price: 65999,
    category: 'Drums',
    brand: 'Zildjian',
    sku: 'DRM-ZIL-ACUSTOM14-001',
    stock: 6,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/440338000000080-00-600x600.jpg'],
    audioSample: null,
    specs: { size: '14 inch', material: 'B20 Bronze' },
  },

  // ---------------- STRINGS ----------------
  {
    name: "D'Addario EXL110 Electric Guitar Strings",
    description: 'Nickel wound, regular light gauge, the industry standard string set.',
    price: 1999,
    category: 'Strings',
    brand: "D'Addario",
    sku: 'STR-DAD-EXL110-001',
    stock: 100,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/H71092000000000-00-600x600.jpg'],
    audioSample: null,
    specs: { gauge: '10-46', material: 'Nickel-plated steel' },
  },
  {
    name: 'Elixir Nanoweb Acoustic Guitar Strings',
    description: 'Coated acoustic strings, longer lifespan and a warm, natural tone.',
    price: 3499,
    category: 'Strings',
    brand: 'Elixir',
    sku: 'STR-ELX-NANOWEB-001',
    stock: 80,
    images: ['https://m1.com.pk/wp-content/uploads/2016/05/Elixir-Acoustci-Nanoweb.jpg'],
    audioSample: null,
    specs: { gauge: '12-53', material: 'Phosphor Bronze, Coated' },
  },
  {
    name: "D'Addario EJ45 Classical Guitar Strings",
    description: 'Nylon strings for classical guitar, balanced tone, normal tension.',
    price: 2499,
    category: 'Strings',
    brand: "D'Addario",
    sku: 'STR-DAD-EJ45-001',
    stock: 60,
    images: ['https://m1.com.pk/wp-content/uploads/2021/05/Daddario-EJ45-458x458.jpg'],
    audioSample: null,
    specs: { tension: 'Normal', material: 'Clear Nylon/Silver-plated Copper' },
  },

  // ---------------- WIND ----------------
  {
    name: 'Yamaha YAS-280 Alto Saxophone',
    description: 'Student-level alto saxophone, easy to play with a warm, even tone across registers.',
    price: 284999,
    category: 'Wind',
    brand: 'Yamaha',
    sku: 'WND-YAM-YAS280-001',
    stock: 3,
    images: ['https://europe.yamaha.com/en/files/yas-280_tcm113-1696630.jpg'],
    audioSample: null,
    specs: { key: 'Eb', finish: 'Gold Lacquer' },
  },
  {
    name: 'Hohner Special 20 Harmonica',
    description: 'Popular diatonic harmonica, plastic comb for airtight seal, used across genres.',
    price: 4999,
    category: 'Wind',
    brand: 'Hohner',
    sku: 'WND-HOH-SPEC20-001',
    stock: 25,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/M22154000000006-00-600x600.jpg'],
    audioSample: null,
    specs: { key: 'C', combMaterial: 'ABS Plastic' },
  },

  // ---------------- AMPS & PEDALS ----------------
  {
    name: 'Fender Frontman 10G Amplifier',
    description: 'Compact 10-watt practice amp, custom-voiced overdrive, great for bedroom practice.',
    price: 16999,
    category: 'Amps & Pedals',
    brand: 'Fender',
    sku: 'AMP-FEN-FRONT10G-001',
    stock: 20,
    images: ['https://waltgracevintage.com/cdn/shop/products/IMG_6314.jpg?v=1605135850&width=823'],
    audioSample: null,
    specs: { wattage: 10, speaker: '6 inch' },
  },
  {
    name: 'Marshall MG15GR Guitar Amplifier',
    description: '15-watt practice amp with built-in reverb, classic Marshall tone at low volume.',
    price: 36999,
    category: 'Amps & Pedals',
    brand: 'Marshall',
    sku: 'AMP-MSH-MG15GR-001',
    stock: 10,
    images: ['https://proaudio.com.pk/wp-content/uploads/2024/10/710x82X5sgL._AC_SL1500_-2.jpg'],
    audioSample: null,
    specs: { wattage: 15, speaker: '8 inch' },
  },
  {
    name: 'Boss DS-1 Distortion Pedal',
    description: 'Iconic distortion pedal, simple 3-knob control, a staple on pedalboards since 1978.',
    price: 16999,
    category: 'Amps & Pedals',
    brand: 'Boss',
    sku: 'AMP-BOSS-DS1-001',
    stock: 20,
    images: ['https://m1.com.pk/wp-content/uploads/2018/03/BOSS-DS-1-Distortion-Pedal.jpg'],
    audioSample: null,
    specs: { type: 'Distortion', power: '9V Battery/Adapter' },
  },
  {
    name: 'Orange Crush 12 Guitar Amp',
    description: 'Compact combo amp with Orange\'s signature crunch, headphone output for silent practice.',
    price: 27999,
    category: 'Amps & Pedals',
    brand: 'Orange',
    sku: 'AMP-ORNG-CRUSH12-001',
    stock: 8,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/J16414000001000-00-600x600.jpg'],
    audioSample: null,
    specs: { wattage: 12, speaker: '6 inch' },
  },

  // ---------------- ACCESSORIES ----------------
  {
    name: 'Dunlop Tortex Standard Picks (12-Pack)',
    description: 'Classic textured guitar picks, consistent grip and durability, assorted gauges.',
    price: 999,
    category: 'Accessories',
    brand: 'Dunlop',
    sku: 'ACC-DUN-TORTEX12-001',
    stock: 200,
    images: ['https://media.guitarcenter.com/is/image/MMGS7/M14973000000001-00-600x600.jpg'],
    audioSample: null,
    specs: { count: 12, gauge: '0.73mm' },
  },
  {
    name: 'Ernie Ball Polypro Guitar Strap',
    description: 'Adjustable, comfortable guitar strap made of durable polypropylene webbing.',
    price: 2499,
    category: 'Accessories',
    brand: 'Ernie Ball',
    sku: 'ACC-ERN-POLYSTRAP-001',
    stock: 50,
    images: ['https://s3.us-west-2.amazonaws.com/static.ernieball.com/website/images/products/image_front/full/P05375.png'],
    audioSample: null,
    specs: { material: 'Polypropylene', adjustable: true },
  },
  {
    name: 'Planet Waves Classic Series Instrument Cable (10ft)',
    description: 'Reliable, noise-free instrument cable, 1/4 inch connectors, 10 feet long.',
    price: 2999,
    category: 'Accessories',
    brand: 'Planet Waves',
    sku: 'ACC-PW-CABLE10-001',
    stock: 60,
    images: ['https://cdn11.bigcommerce.com/s-luvfwivmyi/images/stencil/960w/products/23809/29271/planet-waves-10-classic-series-instrument-cable-1-4-right-angle-plug-9__76283.1657734137.jpg?c=1'],
    audioSample: null,
    specs: { length: '10ft', connector: '1/4 inch TS' },
  },
  {
    name: 'Snark SN-8 Clip-On Tuner',
    description: 'Fast, accurate clip-on tuner for guitar and bass, bright easy-to-read display.',
    price: 2499,
    category: 'Accessories',
    brand: 'Snark',
    sku: 'ACC-SNK-SN8-001',
    stock: 40,
    images: ['https://www.swstrings.com/wp-content/uploads/2024/06/ST-8-1024x1024.jpeg'],
    audioSample: null,
    specs: { type: 'Chromatic Clip-On', display: 'Full color' },
  },
  {
    name: 'Kyser Quick-Change Capo',
    description: 'Spring-loaded capo, one-hand quick change, a standard for acoustic and electric guitars.',
    price: 3499,
    category: 'Accessories',
    brand: 'Kyser',
    sku: 'ACC-KYS-CAPO-001',
    stock: 45,
    images: ['https://kysermusical.com/cdn/shop/files/045A9848.png?v=1747934276&width=1000'],
    audioSample: null,
    specs: { type: 'Spring-loaded', fits: 'Acoustic/Electric' },
  },
  {
    name: 'On-Stage Guitar Stand XCG4',
    description: 'Foldable A-frame guitar stand, fits electric and acoustic guitars safely.',
    price: 3999,
    category: 'Accessories',
    brand: 'On-Stage',
    sku: 'ACC-ONS-STAND-001',
    stock: 30,
    images: ['https://media.sweetwater.com/m/products/image/b52c3a4cd6KDmYEMoBn3oRQ5SSlvgJasP393wLSk.jpg?ha=b52c3a4cd65aab83680aaf1c88f6c461009163b6&quality=82&width=750'],
    audioSample: null,
    specs: { type: 'A-Frame', foldable: true },
  },
]

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('MongoDB connected for seeding')

    await Product.deleteMany({})
    console.log('Old products cleared')

    await Product.insertMany(sampleProducts)
    console.log(`${sampleProducts.length} products seeded successfully`)

    process.exit(0)
  } catch (error) {
    console.error('Seeding error:', error)
    process.exit(1)
  }
}

seedDatabase()